export type Device = { id: string; name: string; kind: 'desktop' | 'ios' | 'android' | 'web'; online?: boolean };
export type Group = { id: string; name: string; baseUrl: string; key: string; hostDeviceId?: string; legacy?: boolean };
export type Message = { id: string; type: 'text' | 'file'; text?: string; fileName?: string; size?: number; mime?: string; sha256?: string; senderId: string; senderName: string; createdAt: string };
export type GroupState = { messages: Message[]; devices: Device[]; maxFileBytes?: number; type?: 'state' };
export type ConnectionStatus = 'connecting' | 'online' | 'offline' | 'paused';
export type JoinStatus = 'pending' | 'approved' | 'denied' | 'expired';
export type JoinTicket = { status: 'pending'; requestId: string; pollToken: string; groupId: string; groupName: string; hostDeviceId: string; expiresAt: number; baseUrl: string };
export type JoinRequest = { id: string; requestId: string; device: Device; createdAt: number; expiresAt: number; status: JoinStatus };
export type Invite = { code: string; expiresAt: number; groupId: string; link: string };
export type Session = { device: Device; groups: Group[]; activeGroupId: string | null };
export type Storage = { getItemAsync(key: string): Promise<string | null>; setItemAsync(key: string, value: string): Promise<void>; deleteItemAsync?(key: string): Promise<void> };
export type RequestOptions = { method?: string; body?: unknown; headers?: Record<string, string>; signal?: AbortSignal };
export type JoinOptions = { signal?: AbortSignal; onStatus?: (status: JoinStatus) => void; intervalMs?: number };
export type GroupWatch = { groupId: string; setActive(active: boolean): void; close(): void };
export type MobileClient = {
  init(): Promise<Session>;
  readonly device: Device;
  getSession(): Session;
  listGroups(): Group[];
  getGroup(id: string): Group;
  authHeaders(id: string): Record<string, string>;
  verifyGroup(id: string, options?: Pick<RequestOptions, 'signal'>): Promise<{ groupId: string; hostDeviceId: string; proof: string }>;
  api<T = any>(id: string, route: string, options?: RequestOptions): Promise<T>;
  setActiveGroup(id: string | null): Promise<void>;
  removeGroup(id: string): Promise<void>;
  rename(name: string): Promise<Device>;
  requestJoinAt(baseUrl: string, code: string, options?: Pick<JoinOptions, 'signal'>): Promise<JoinTicket>;
  requestJoin(link: string, options?: Pick<JoinOptions, 'signal'>): Promise<JoinTicket>;
  checkJoin(ticket: JoinTicket, options?: Pick<JoinOptions, 'signal'>): Promise<{ status: JoinStatus; group?: Group }>;
  waitForJoin(ticket: JoinTicket, options?: JoinOptions): Promise<Group>;
  joinLink(link: string, options?: JoinOptions): Promise<Group>;
  createInvite(id: string, options?: Pick<RequestOptions, 'signal'>): Promise<Invite>;
  listJoinRequests(id: string, options?: Pick<RequestOptions, 'signal'>): Promise<JoinRequest[]>;
  respondJoin(id: string, requestId: string, allow: boolean, options?: Pick<RequestOptions, 'signal'>): Promise<{ status: JoinStatus }>;
  watchGroup(id: string, options?: { onState?: (state: GroupState) => void; onStatus?: (status: ConnectionStatus) => void; onError?: (error: Error) => void; active?: boolean }): GroupWatch;
  close(): void;
};
export function parseInviteLink(value: string): { baseUrl: string; code: string; groupId?: string; legacy: false } | { baseUrl: string; key: string; legacy: true };
export function createMobileClient(options: { storage: Storage; randomUUID: () => string; deviceName?: string; kind?: Device['kind']; fetchImpl?: typeof fetch; WebSocketImpl?: typeof WebSocket; requestTimeoutMs?: number; reconnectMs?: number }): MobileClient;
