import React from 'react';
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, palette } from './ui';
import type { DiscoverySnapshot, NearbyGroup } from '../discovery-core';

type Props = { snapshot: DiscoverySnapshot; selected: NearbyGroup | null; code: string; joinedIds: string[]; busy: boolean; onSelect(group: NearbyGroup): void; onCode(value: string): void; onJoin(): void; onRefresh(): void; onBack(): void };
export function NearbyGroups({ snapshot, selected, code, joinedIds, busy, onSelect, onCode, onJoin, onRefresh, onBack }: Props) {
  const available = selected && snapshot.devices.some(item => item.groupId === selected.groupId && item.hostDeviceId === selected.hostDeviceId && item.baseUrl === selected.baseUrl);
  if (selected) return <View><Button compact label="‹ 返回附近列表" onPress={onBack} /><View style={s.selectedCard}><Text style={s.computer}>▱</Text><Text style={s.selectedName}>{selected.name}</Text><Text style={s.caption}>{available ? '已找到这台电脑上的传输群' : '这台电脑暂时不在附近列表中'}</Text></View><Text style={s.help}>在电脑的群菜单中打开「邀请设备」，输入上面的 6 位邀请码。电脑允许后，即可一起传文件。</Text><TextInput testID="nearby-code" accessibilityLabel="附近电脑的6位邀请码" keyboardType="number-pad" maxLength={6} value={code} onChangeText={value => onCode(value.replace(/\D/g, '').slice(0, 6))} style={s.code} placeholder="000000" placeholderTextColor="#bcc8d8" /><Button primary label={`申请加入${selected.name}`} disabled={busy || code.length !== 6 || !available} onPress={onJoin} />{!available && <View style={s.retry}><Button label="重新查找附近设备" onPress={onRefresh} disabled={busy} /></View>}</View>;
  return <View><View style={s.heading}><Text accessibilityRole="header" style={s.title}>附近的传输群</Text><Button compact label="刷新" accessibilityLabel="刷新附近设备" onPress={onRefresh} disabled={busy || snapshot.status === 'unavailable'} /></View>
    {(snapshot.status === 'scanning' || snapshot.status === 'ready') && <View style={s.searching}><ActivityIndicator size="small" color={palette.blue} /><Text style={s.caption}>{snapshot.devices.length ? '正在查找同一网络中的其他设备' : '正在查找同一网络中的电脑…'}</Text></View>}
    {snapshot.devices.map(group => <Pressable key={`${group.groupId}:${group.hostDeviceId}`} accessibilityRole="button" accessibilityLabel={`${joinedIds.includes(group.groupId) ? '连接' : '选择'}附近群${group.name}`} disabled={busy} onPress={() => onSelect(group)} style={({ pressed }) => [s.row, pressed && { opacity: .65 }]}><View style={s.deviceMark}><Text style={s.deviceGlyph}>▱</Text></View><View style={s.info}><Text numberOfLines={1} style={s.name}>{group.name}</Text><Text style={s.caption}>{joinedIds.includes(group.groupId) ? '已加入 · 点击连接' : '已发现 · 输入邀请码加入'}</Text></View><Text style={s.chevron}>›</Text></Pressable>)}
    {['empty', 'error', 'permission-denied', 'unavailable'].includes(snapshot.status) && <View testID={`discovery-${snapshot.status}`} accessibilityLiveRegion="polite" style={s.stateCard}><Text style={s.stateTitle}>{snapshot.status === 'unavailable' ? '此环境不支持附近发现' : snapshot.status === 'permission-denied' ? '请允许本地网络访问' : snapshot.status === 'error' ? '暂时无法查找' : '还没找到附近的电脑'}</Text><Text style={s.help}>{snapshot.message}</Text>{snapshot.status === 'permission-denied' && <Button label="打开系统设置" onPress={() => { Linking.openSettings().catch(() => {}); }} />}{snapshot.status !== 'unavailable' && snapshot.status !== 'permission-denied' && <Text style={s.caption}>也可以使用下方扫码，或展开高级连接。</Text>}</View>}
  </View>;
}
const s = StyleSheet.create({
  heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }, title: { fontSize: 15, fontWeight: '600', color: palette.ink }, searching: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 12 }, caption: { fontSize: 11, lineHeight: 19, color: '#93a3ba', flexShrink: 1 }, row: { paddingVertical: 17, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#e9f0fa' }, deviceMark: { width: 43, height: 43, borderRadius: 13, backgroundColor: '#edf5ff', alignItems: 'center', justifyContent: 'center' }, deviceGlyph: { color: '#4a8fef', fontSize: 27 }, info: { flex: 1, gap: 5 }, name: { fontSize: 14, fontWeight: '500', color: '#3c577a' }, chevron: { fontSize: 26, color: '#adc1db' }, stateCard: { padding: 17, backgroundColor: '#f4f8ff', borderRadius: 13, marginTop: 13, gap: 10 }, stateTitle: { color: '#6b86ab', fontSize: 13, fontWeight: '500' }, help: { fontSize: 12, color: '#8a9db8', lineHeight: 22 }, selectedCard: { alignItems: 'center', paddingVertical: 25, gap: 9 }, computer: { fontSize: 48, color: '#5c9af0' }, selectedName: { color: palette.ink, fontWeight: '600', fontSize: 20 }, code: { borderWidth: 1, borderColor: '#dfe8f5', borderRadius: 12, padding: 14, marginVertical: 20, color: palette.ink, fontSize: 29, letterSpacing: 9, textAlign: 'center' }, retry: { marginTop: 12 },
});
